### ISSUE TITLE
insertHook 与 deleteHook 设计是否需要保留

### ISSUE THREAD

**Issue by Brooooooklyn** [teambition/ReactiveDB#33]
`InsertHook` 最初的设计目的是为了在插入含 Virtual 类型字段的 table 的时候分离 Virtual 数据并插入数据表：

```ts
TaskSchemaDef: {
  _id: {
    type: RDBType.string,
    primary: true
  },
  project: {
    type: Association.oneToMany,
    virtual: {
      name: 'Project',
      where: projectTable => ({
        _projectId: projectTable._id
      })
    }
  }
}
```
但在实际应用场景中，并没有业务需要调用 insertHook

而对于 `deleteHook`，当初设计它是为了在某些数据删除的时候，同时删除与它关联的数据，比如`删除任务的时候同时删除它的子任务和关联`。但在实际业务中 hook 的定义非常难写，并且很难保持它的`原子性`。

所以根据以下的理由:

1. InsertHook 应用场景非常有限
2. DeleteHook 还没有一个非常合理的设计
3. 只有 insert 与 delete hook 对于 ReactiveDB 来说定义是不完整的
4. 很难保证这些 hook 的原子性

我们需要重新设计 Hook 吗，还是对外不暴露这些接口？

**Comment by Saviio** [comment]
我觉得要重新设计， hiddenMapper的机制要保留，这个不怀疑， 但是这个hook的能力其实是超级弱化版的trigger，而且以现在的设计这个hook的设计一方面要拖慢lf的perf，另一方面现有的实现没办法做到Failed/Succeed together，显得鸡肋。

upsertVirtualProp这个方法我从一开始就持有一点保留态度，两个原因：
1. 这段代码并不好看，而且行为其实比较奇怪，导致我没办法从一个比较小的切入点上做重构。
2. 因为hook的存在导致insert的接口的返回值(现在没有，但suppose将来会支持)其实是没办法做到和schema定义一致的，或者说做到接口的一致性成本很高，这样其实是不优雅的。当然你可以说这样一来get就和I/U/D三个方法不一致，但其实不然，get是read， 但I/U/D三个都是write，这三个同属性的方法出现不一致，我觉得就是设计上的失误。

keep it simple stupid，get/insert/delete/update 各个接口维护单一职能显然是最正交的做法。如果insert要做virtual的更新，其实唯一的收益就是「偷懒」，但引入的后果就是灵活性降低而且平添不必要的复杂度，风险比收益大。

所以我现在直觉上判断data flatten应该外置，不用insert hook做。另外一个原因是因为想到sdk大概率会面临update or insert的策略选择，我个人考虑是在sdk这里引入一个很薄的cache层(可能并不需要map，也不需要expiration)，我还需要和yn讨论分析一下场景，另外可能有必要参考一下relay的设计(我之前看过一部分，觉得可能可以解决一些问题。

以上是我最近写DLS的时候在思考的RDB问题的结论....
